### PR TITLE
Mikrotik backup implementation

### LINKED ISSUE #11: Mikrotik backup implementation
Mikrotik backups via ssh.

Access to the router (ssh)
- Passing password as clear text with **[sshpass](https://www.cyberciti.biz/faq/noninteractive-shell-script-ssh-password-provider/)** (not recommended)
- [Using ssh keys](https://jcutrer.com/howto/networking/mikrotik/routeros-ssh-publickeyauth-rsa-keys) (recommended)

Commands to be executed
- Run backup : `ssh admin@router /system backup save name="<backup_name>"`
- Get backup from router : `scp admin@router:"<backup_name>" <local_dir>` 

Other commands that can be useful
- Export scripts : `/system script export file=scripts`
- Export system configuration : `/system export file=system`
- Export global configuration as .rsc : `/export file=router`

It would be nice to : 
- Save the backup as something like : "$hostname-$date" (majorcadevs-12-03-2019)
- Delete past day backup and always keep the daily backup at the router

### PR DESCRIPTION
**Pull request by amgxv**
Tested in VSCode Live Share and working.
Now Mikrotik Backups are fully working with and without ssh key.

Closes #11

### CODE REVIEW

**Comment by melchor629** [comment]
Linked to #11

**Review by melchor629 — APPROVED** [review]
Seems ok 🗿

**Comment by Alkesst** [comment]
Seems legit

**Review by Alkesst — APPROVED** [review]
Seems legit x2

**Pull request merged**
